import crypto from 'node:crypto'
import tls from 'node:tls'
import forge from 'node-forge'

/**
 * TLS helpers shared by the proxy E2E suites.
 *
 * These suites used to open with `process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0'`,
 * which switches certificate verification off for every socket in the worker —
 * including the ones the test is asserting on. Two things came of that: CodeQL
 * flagged it (js/disabling-certificate-validation), and, worse, the suites could
 * not have noticed the proxy serving a chain no real client would accept. The
 * mock upstream's certificate had no subjectAltName at all and the tests still
 * passed.
 *
 * Instead: generate a real CA for the mock upstream, add it to the process trust
 * store for the lifetime of the file, and leave verification on everywhere.
 */

/** A CA plus a server certificate issued by it, all PEM. */
export interface UpstreamCert {
  /** PEM of the CA — feed to `trustCA` so the proxy's outbound leg accepts it. */
  ca: string
  /** Server key, for `https.createServer`. */
  key: string
  /** Server certificate chain (leaf then CA), for `https.createServer`. */
  cert: string
}

/**
 * RSA-2048 keypair, in the shape node-forge wants for signing.
 *
 * Generated by node:crypto rather than `forge.pki.rsa.generateKeyPair`, which is
 * pure JS: two forge keygens in one beforeAll hook blew past the suite's 120 s
 * hook timeout on Windows. The native generator is not close to the limit.
 */
function keypair(): { privateKey: forge.pki.PrivateKey; publicKey: forge.pki.PublicKey; pem: string } {
  const { privateKey, publicKey } = crypto.generateKeyPairSync('rsa', { modulusLength: 2048 })
  const pem = privateKey.export({ type: 'pkcs1', format: 'pem' }).toString()
  return {
    privateKey: forge.pki.privateKeyFromPem(pem),
    publicKey: forge.pki.publicKeyFromPem(publicKey.export({ type: 'spki', format: 'pem' }).toString()),
    pem,
  }
}

/**
 * Issue a server certificate for `host` from a throwaway CA.
 *
 * The leaf carries a subjectAltName, which is what Node actually checks —
 * commonName alone has not been accepted since Node 18, and the old fixtures
 * only got away with it because verification was off.
 */
export function issueUpstreamCert(host = 'api.anthropic.com'): UpstreamCert {
  const caKeys = keypair()
  const ca = forge.pki.createCertificate()
  ca.publicKey = caKeys.publicKey
  ca.serialNumber = '01'
  ca.validity.notBefore = new Date()
  ca.validity.notAfter = new Date()
  ca.validity.notAfter.setFullYear(ca.validity.notBefore.getFullYear() + 1)
  const caAttrs = [{ name: 'commonName', value: 'llm-fw test upstream CA' }]
  ca.setSubject(caAttrs)
  ca.setIssuer(caAttrs)
  ca.setExtensions([
    { name: 'basicConstraints', cA: true, critical: true },
    { name: 'keyUsage', keyCertSign: true, cRLSign: true, critical: true },
  ])
  ca.sign(caKeys.privateKey as forge.pki.rsa.PrivateKey, forge.md.sha256.create())

  const leafKeys = keypair()
  const leaf = forge.pki.createCertificate()
  leaf.publicKey = leafKeys.publicKey
  leaf.serialNumber = '02'
  leaf.validity.notBefore = new Date()
  leaf.validity.notAfter = new Date()
  leaf.validity.notAfter.setFullYear(leaf.validity.notBefore.getFullYear() + 1)
  leaf.setSubject([{ name: 'commonName', value: host }])
  leaf.setIssuer(caAttrs)
  leaf.setExtensions([
    { name: 'basicConstraints', cA: false, critical: true },
    { name: 'keyUsage', digitalSignature: true, keyEncipherment: true, critical: true },
    { name: 'extKeyUsage', serverAuth: true },
    { name: 'subjectAltName', altNames: [{ type: 2, value: host }] }, // type 2 = dNSName
  ])
  leaf.sign(caKeys.privateKey as forge.pki.rsa.PrivateKey, forge.md.sha256.create())

  const caPem = forge.pki.certificateToPem(ca)
  return { ca: caPem, key: leafKeys.pem, cert: forge.pki.certificateToPem(leaf) + caPem }
}

/**
 * Add `caPem` to the process-wide default trust store and return an undo.
 *
 * Process-wide is the requirement, not a convenience: the connection that has to
 * accept the mock upstream is the one ProxyServer opens itself (`tls.connect` in
 * forwardRequest), so there is no options object the test can reach. Call the
 * returned function in `afterAll` — vitest reuses a worker across files, and a
 * leaked trust anchor would silently widen the next suite.
 */
export function trustCA(caPem: string): () => void {
  const previous = tls.getCACertificates('default')
  tls.setDefaultCACertificates([...previous, caPem])
  return () => { tls.setDefaultCACertificates(previous) }
}
